name: 'Deploy Vapor'
description: 'Deploys a Vapor app to Vapor Cloud'
inputs:
  app:
    description: 'Application to deploy'
    required: true
  env:
    description: 'Environment to deploy'
    required: true
  branch:
    description: 'Branch to deploy'
    required: true
runs:
  using: 'docker'
  image: 'docker://vapor/toolbox:18'
  args:
    - cloud
    - deploy
    - --app
    - ${{ inputs.app }}
    - --env
    - ${{ inputs.env }}
    - --branch
    - ${{ inputs.branch }}
